{"comments": {}, "bugs": {"669518": {"comments": [{"id": 5575270, "attachment_id": 544100, "raw_text": "I believe this is related to bug 644697.\n\nRunning Narcissus with jstests.py fails with Tracemonkey branch (though I think the issue is larger than Narcissus).  Here is the error:\n\nTraceback (most recent call last):\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/jstests.py\", line 309, in <module>\n    test_list = manifest.parse(OPTIONS.manifest, xul_tester)\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 125, in parse\n    ans += parse(os.path.join(dir, include_file), xul_tester, include_reldir)\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 125, in parse\n    ans += parse(os.path.join(dir, include_file), xul_tester, include_reldir)\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 159, in parse\n    if xul_tester.test(cond):\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 96, in test\n    % (cond, out, err))\nException: Failed to test XUL condition '!xulRuntime.shell'; output was '', stderr was ':1: ReferenceError: False is not defined\\n'\n\n\nA patch is attached.  The key change to manifest.py is listed here, for convenience:\n-            self.os == \"Android\")\n+            str(self.os == \"Android\").lower())", "author": "taustin@ucsc.edu", "creation_time": "2011-07-05T23:52:25Z", "tags": [], "bug_id": 669518, "time": "2011-07-05T23:52:25Z", "text": "Created attachment 544100\nPatch file\n\nI believe this is related to bug 644697.\n\nRunning Narcissus with jstests.py fails with Tracemonkey branch (though I think the issue is larger than Narcissus).  Here is the error:\n\nTraceback (most recent call last):\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/jstests.py\", line 309, in <module>\n    test_list = manifest.parse(OPTIONS.manifest, xul_tester)\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 125, in parse\n    ans += parse(os.path.join(dir, include_file), xul_tester, include_reldir)\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 125, in parse\n    ans += parse(os.path.join(dir, include_file), xul_tester, include_reldir)\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 159, in parse\n    if xul_tester.test(cond):\n  File \"/Users/taustin/mozilla/tracemonkey/js/src/tests/manifest.py\", line 96, in test\n    % (cond, out, err))\nException: Failed to test XUL condition '!xulRuntime.shell'; output was '', stderr was ':1: ReferenceError: False is not defined\\n'\n\n\nA patch is attached.  The key change to manifest.py is listed here, for convenience:\n-            self.os == \"Android\")\n+            str(self.os == \"Android\").lower())", "creator": "taustin@ucsc.edu", "is_private": false, "count": 0}]}}}